---
- name: Append my.cnf
  blockinfile:
    path: /etc/mysql/my.cnf
    block: |
      [mysqld]
      character-set-client-handshake = FALSE
      character-set-server = utf8mb4
      collation-server = utf8mb4_unicode_ci

      [mysql]
      default-character-set = utf8mb4
  notify: restart mysql
