---
- hosts: server1
  become: yes

  tasks:
    - name: SSH
      include_role:
        name: security
        tasks_from: ssh

    - name: UFW
      include_role:
        name: security
        tasks_from: ufw

    - name: Timezone
      include_role:
        name: ubuntu
        tasks_from: timezone

    - name: System
      include_role:
        name: ubuntu

    - name: Postfix
      include_role:
        name: postfix

    - name: Unattended-updates
      include_role:
        name: security
        tasks_from: unattended-updates

    - name: Users
      include_role:
        name: ubuntu
        tasks_from: useradd
